### ISSUE TITLE
New Features to be added

### ISSUE THREAD

**Issue by VirangParekh** [VirangParekh/Pitch-Desktop-App#11]
- [x] Search functionality
- [x] Podcast Upload
- [x] Album Edit
- [x] Album Stats
    - [x] Album Name
    - [x] Album Songs played
- [x] Trending Songs and Podcasts

**Comment by Utsav-Unadkat** [comment]
@VirangParekh Please make Search functionality as you priority as then i can test it out with ajax on the frontend too

**Comment by VirangParekh** [comment]
@Utsav-Unadkat done in #15
